name: Package QuestProgressSound

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'   # läuft nur, wenn ein Tag v... gepusht wird

jobs:
  package:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run BigWigs packager
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}